services: 
  db: 
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass' 
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose: 
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
